### PR TITLE
Generator Refactor

### LINKED ISSUE #9: no admin page
Hi,

After installation of the version MSR1: 0.5.2 the installation and website start fine.
Going to `.../ghost` it open the first dialog to put website name, username, password.
Clicking `continue` it open correctly `.../ghost/1/` page, but the page is blank.

Best,
Andrea

### PR DESCRIPTION
**Pull request by acburdine**
closes #9, #10, #11, #12

This refactors and updates the ghost generator to use the newest yeoman-generator syntax, as well as improving some of the configurability of the generator.

TODO:
- [x] get the basic ghost-generator command updated and working
- [x] get the casper copy command updated and working
- [x] tests

### CODE REVIEW

**Comment by sethvincent** [comment]
Nice! I'm happy to turn over this module to you, or at least add you as a collaborator.

I haven't been using Ghost much lately so haven't worked on this as much as I should.

**Comment by acburdine** [comment]
@sethvincent sounds good 😄  Do you want me to help out with npm releases too?

**Comment by sethvincent** [comment]
Sure! You're now a collaborator on github & npm.

**Comment by acburdine** [comment]
Hey @sethvincent would you be willing to enable Travis for this repository? I can't with my current access permissions.

**Comment by sethvincent** [comment]
@acburdine enabled!

Looks like we'll need to update the travis.yml file. Feel free to include that in this PR.

**Comment by acburdine** [comment]
@sethvincent good to go now! If you want to merge it go ahead, once that's done I'll release 0.3

**Comment by sethvincent** [comment]
:tada:

**Pull request merged**
